### ISSUE TITLE
what is the difference between this runner?

### ISSUE THREAD

**Issue by cottsak** [4Com/team-city-xunit-meta-runner#6]
and this one https://github.com/JetBrains/meta-runner-power-pack/tree/master/xUnit.net-dotCover ?

**Comment by mattridgway** [comment]
This runner was created almost two years ago to fill a gap we had at the time in supporting xunit2.

Back then the only compatible meta runner we could find was https://github.com/rhysgodfrey/team-city-xunit-meta-runner which was targeted specifically at xunit v1.

Looks like your version is more feature complete to allow for wildcarding, traits and dotcover.

**Comment by cottsak** [comment]
Thanks for clearing that up.

Are you interested in forwarding users to the other plugin given what you've said. I notice that the info for getting xunit set up in TC is sketchy at best so when folks find themselves at different ends of the internet I think it makes things harder. 

I can propose a change to your `readme.md` file if you like if perhaps you don't have the time?

**Comment by herecydev** [comment]
Resolved by #7
